/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.AkunController;
import Controller.KeranjangController;
import Controller.MakananController;
import Controller.TokoController;
import Controller.TransaksiController;
import Model.DriverOnlineShop;
import Model.UserSession;
import javax.swing.JOptionPane;

/**
 *
 * @author Rafif Purnomo
 */
public class Checkout extends javax.swing.JFrame {

    /**
     * Creates new form Checkout
     */
    private MakananController makananCNTRL;
    private AkunController akunCNTRL;
    private TokoController tokoCNTRL;
    private KeranjangController keranjangCNTRL;
    private TransaksiController transaksiCNTRL;
    private DriverOnlineShop driver;
    
    public int id_keranjang, id_makanan, banyakPorsi, id_user;
    public String namaMakanan, namaRestaurant;
    public double harga;
    
    public Checkout() {
        driver = new DriverOnlineShop(this);
        makananCNTRL = new MakananController();
        tokoCNTRL = new TokoController();
        keranjangCNTRL = new KeranjangController();
        transaksiCNTRL = new TransaksiController();
        
        initComponents();
    }

    public void Checkout(int id_keranjang,int id_user, int id_makanan, int banyakPorsi, String namaMakanan, String namaRestaurant, double harga) {
        this.id_keranjang = id_keranjang;
        this.id_user = id_user;
        this.id_makanan = id_makanan;
        this.banyakPorsi = banyakPorsi;
        this.namaMakanan = namaMakanan;
        this.namaRestaurant = namaRestaurant;
        this.harga = harga;
    
        namaMakananDisplay.setText(namaMakanan);
//        namaRestaurantDisplay.setText(namaRestaurant);
        banyakPorsiDisplay.setText(String.valueOf(banyakPorsi));
        totalhargaDisplay.setText(String.valueOf(harga));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        totalhargaDisplay = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        banyakPorsiDisplay = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        BatalkanPesananBTN = new javax.swing.JButton();
        CheckoutBTN = new javax.swing.JButton();
        namaMakananDisplay = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        kembaliBTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(196, 202, 196));

        totalhargaDisplay.setText("Harga Makanan");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setText("Total Harga");

        banyakPorsiDisplay.setText("Porsi Makanan");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setText("Porsi Pesanan");

        BatalkanPesananBTN.setBackground(new java.awt.Color(255, 102, 102));
        BatalkanPesananBTN.setText("Batalkan Pesanan");
        BatalkanPesananBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BatalkanPesananBTNActionPerformed(evt);
            }
        });

        CheckoutBTN.setBackground(new java.awt.Color(85, 102, 85));
        CheckoutBTN.setText("Checkout Pesanan");
        CheckoutBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckoutBTNActionPerformed(evt);
            }
        });

        namaMakananDisplay.setText("Nama Makanan");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("Pesanan Makanan");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        jLabel1.setText("Checkout Pesanan Makanan");

        kembaliBTN.setFont(new java.awt.Font("Segoe UI", 1, 21)); // NOI18N
        kembaliBTN.setText("<-");
        kembaliBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(351, 351, 351)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(namaMakananDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(banyakPorsiDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(totalhargaDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(285, 285, 285)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(BatalkanPesananBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(CheckoutBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 286, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(kembaliBTN)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(kembaliBTN)
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(62, 62, 62)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(namaMakananDisplay)
                .addGap(45, 45, 45)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(banyakPorsiDisplay)
                .addGap(47, 47, 47)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(totalhargaDisplay)
                .addGap(73, 73, 73)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BatalkanPesananBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CheckoutBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(79, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CheckoutBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckoutBTNActionPerformed
        boolean status = transaksiCNTRL.tambahHistoryTransaksi(UserSession.getId(), namaMakanan, banyakPorsi, harga, "selesai");
        if (status) {
            keranjangCNTRL.hapusKeranjang(id_keranjang);
            driver.statusCheckoutBerhasil(status);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan pada checkout");
        }
        
    }//GEN-LAST:event_CheckoutBTNActionPerformed

    private void BatalkanPesananBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BatalkanPesananBTNActionPerformed
        boolean status = transaksiCNTRL.tambahHistoryTransaksi(UserSession.getId(), namaMakanan, banyakPorsi, harga, "dibatalkan");
        if (status) {
            keranjangCNTRL.hapusKeranjang(id_keranjang);
            driver.statusCheckoutDiBatalkan(status);
        } else {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan pada pembatalan pesanan");
        }
        
    }//GEN-LAST:event_BatalkanPesananBTNActionPerformed

    private void kembaliBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliBTNActionPerformed
        this.dispose();
    }//GEN-LAST:event_kembaliBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Checkout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Checkout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Checkout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Checkout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Checkout().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BatalkanPesananBTN;
    private javax.swing.JButton CheckoutBTN;
    private javax.swing.JLabel banyakPorsiDisplay;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton kembaliBTN;
    private javax.swing.JLabel namaMakananDisplay;
    private javax.swing.JLabel totalhargaDisplay;
    // End of variables declaration//GEN-END:variables
}
