/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.KeranjangController;
import Controller.MakananController;
import Controller.TokoController;
import Controller.TransaksiController;
import Model.DriverOnlineShop;
import Model.UserSession;
import Model.Toko;
import Model.Keranjang;
import Model.Transaksi;
import static java.awt.Frame.NORMAL;
import static java.awt.image.ImageObserver.ERROR;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Muhammad Rafif A.P
 */
public class MenuPembeli extends javax.swing.JFrame {

    /**
     * Creates new form MenuPembeli
     */
    
    private DriverOnlineShop driver;
    private TokoController tokoCNTRL;
    private MakananController mknCNTRL;
    private KeranjangController keranjangCNTRL;
    private TransaksiController transaksiCNTRL;
    private DefaultTableModel table_model, tableModelKeranjang, tableModelTransaksi;
    public double totalHargaKeranjang;
    
    public MenuPembeli() {
        driver = new DriverOnlineShop(this);
        tokoCNTRL = new TokoController();
        mknCNTRL = new MakananController();
        keranjangCNTRL = new KeranjangController();
        transaksiCNTRL = new TransaksiController();
        
        initComponents();
        int idUser = UserSession.getId();
        
        String namaUser = UserSession.getNama();
        String noTelpon = UserSession.getNoTelpon();
        String Username = UserSession.getUsername();
        
        NamaUserHome.setText(namaUser);
        NamaUserProfile.setText(namaUser);
        NoTelpUserProfile.setText(noTelpon);
        UsernameUserProfile.setText(Username);        
        
        String[] judulTabel = {"id toko", "nama toko", "alamat toko"};
        table_model = new DefaultTableModel(judulTabel, 0);
        daftarTokoMakanan.setModel(table_model);
        loadToko();
        
        String[] judulTableKeranjang =  {"id Keranjang", "id Makanan","nama makanan", "jumlah pesanan", "harga"};
        tableModelKeranjang = new DefaultTableModel(judulTableKeranjang, 0);
        TableKeranjang.setModel(tableModelKeranjang);
        
        loadKeranjang(idUser);
        totalKeranjangDisplay.setText(String.valueOf(totalHargaKeranjang));
        
        String[] judulTableRiwayatTransaksi = {"id transaksi", "nama makanan", "jumlah pesanan", "harga", "status"};
        tableModelTransaksi = new DefaultTableModel(judulTableRiwayatTransaksi, 0);
        tableRiwayatTransaksi.setModel(tableModelTransaksi);
        loadTransaksi(idUser);
        
    }
    
    private void loadKeranjang(int idUser){
        List<Keranjang> dataKeranjang = keranjangCNTRL.getKeranjangByAkun(idUser);
        
        for(Keranjang keranjang : dataKeranjang){
            Object[] rowDataKeranjang = {
                keranjang.getId_keranjang(),
                keranjang.getId_makanan(),
                keranjang.getNama_makanan(),
                keranjang.getBanyak_makanan(),
                keranjang.getTotal_harga()
            };
            tableModelKeranjang.addRow(rowDataKeranjang);
           totalHargaKeranjang += keranjang.getTotal_harga();
        }   
    }
    
    private void loadTransaksi(int idUser){
        List<Transaksi> dataTransaksi = transaksiCNTRL.getAllRiwayatTransaksi(idUser);
     
        for(Transaksi transaksi : dataTransaksi){
            Object[] rowRiwayatTransaksi = {
                transaksi.getId_transaksi(),
                transaksi.getNamaMakanan(),
                transaksi.getTotalPesanan(),
                transaksi.getHarga(),
                transaksi.getStatusPesanan()
            };
            tableModelTransaksi.addRow(rowRiwayatTransaksi);
        }
    }
    
    private void loadToko(){
        List<Toko> dataToko = tokoCNTRL.getAllToko();
        
        for(Toko toko : dataToko){
            Object[] rowData = {
                toko.getId_toko(),
                toko.getNamaToko(),
                toko.getAlamatToko()
        };
        table_model.addRow(rowData);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MenuPembeli = new javax.swing.JTabbedPane();
        HomePembeli = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        SelamatDatang = new javax.swing.JLabel();
        NamaUserHome = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cariToko = new javax.swing.JTextField();
        cariTokoBTN = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        daftarTokoMakanan = new javax.swing.JTable();
        updateDaftarTokoBTN = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        KeranjangPembeli = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableKeranjang = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        totalKeranjangDisplay = new javax.swing.JLabel();
        refreshBTN = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableRiwayatTransaksi = new javax.swing.JTable();
        updateRiwayatTransaksi = new javax.swing.JButton();
        ProfilePembeli = new javax.swing.JPanel();
        LogoutBTN = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        UsernameUserProfile = new javax.swing.JLabel();
        NamaUserProfile = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        NoTelpUserProfile = new javax.swing.JLabel();
        UbahNama = new javax.swing.JButton();
        UbahUsername = new javax.swing.JButton();
        UbahNoTelpon = new javax.swing.JButton();
        UbahPassword = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MenuPembeli.setBackground(new java.awt.Color(85, 102, 85));
        MenuPembeli.setForeground(new java.awt.Color(85, 102, 85));
        MenuPembeli.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel2.setBackground(new java.awt.Color(196, 202, 196));

        SelamatDatang.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        SelamatDatang.setText("Selamat datang di FreshApp");

        NamaUserHome.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        NamaUserHome.setText("Nama");

        cariTokoBTN.setBackground(new java.awt.Color(85, 102, 85));
        cariTokoBTN.setText("Cari");
        cariTokoBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariTokoBTNActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setText("Daftar toko makanan");

        daftarTokoMakanan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        daftarTokoMakanan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                daftarTokoMakananMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(daftarTokoMakanan);

        updateDaftarTokoBTN.setBackground(new java.awt.Color(85, 102, 85));
        updateDaftarTokoBTN.setText("Refresh Pencarian");
        updateDaftarTokoBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateDaftarTokoBTNActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel10.setText("Mencari makanan enak untuk anda");

        jLabel11.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel11.setText("Kami menawarkan pengalaman kuliner yang tidak hanya mengenyangkan perut, tapi juga hati");

        jLabel12.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel12.setText("Nikmati hidangan lezat kami, dan rasakan kehangatan kami.");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 817, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(152, 152, 152)
                                .addComponent(jLabel10))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(SelamatDatang)
                                .addGap(236, 236, 236)))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(139, 139, 139)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(updateDaftarTokoBTN)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(575, 575, 575))))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(189, 189, 189)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel11)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel12)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(cariToko, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(cariTokoBTN)))
                                    .addGap(110, 110, 110))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addComponent(NamaUserHome)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel10))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(NamaUserHome)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(jLabel3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel11)
                        .addGap(1, 1, 1)
                        .addComponent(jLabel12)
                        .addGap(29, 29, 29)
                        .addComponent(SelamatDatang)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cariToko, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cariTokoBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(51, 51, 51)
                        .addComponent(jLabel4)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(updateDaftarTokoBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout HomePembeliLayout = new javax.swing.GroupLayout(HomePembeli);
        HomePembeli.setLayout(HomePembeliLayout);
        HomePembeliLayout.setHorizontalGroup(
            HomePembeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        HomePembeliLayout.setVerticalGroup(
            HomePembeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        MenuPembeli.addTab("Home", HomePembeli);

        KeranjangPembeli.setBackground(new java.awt.Color(196, 202, 196));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        jLabel5.setText("Keranjang Pesanan");

        jLabel7.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel7.setText("Ayo checkout sebelum perut anda memberontak!!");

        TableKeranjang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TableKeranjang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableKeranjangMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TableKeranjang);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setText("Total keranjang Pesanan");

        totalKeranjangDisplay.setFont(new java.awt.Font("Segoe UI", 0, 21)); // NOI18N
        totalKeranjangDisplay.setText("total keranjang");

        refreshBTN.setBackground(new java.awt.Color(85, 102, 85));
        refreshBTN.setText("Refresh");
        refreshBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout KeranjangPembeliLayout = new javax.swing.GroupLayout(KeranjangPembeli);
        KeranjangPembeli.setLayout(KeranjangPembeliLayout);
        KeranjangPembeliLayout.setHorizontalGroup(
            KeranjangPembeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, KeranjangPembeliLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(KeranjangPembeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, KeranjangPembeliLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(25, 25, 25)))
                .addGap(369, 369, 369))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, KeranjangPembeliLayout.createSequentialGroup()
                .addContainerGap(140, Short.MAX_VALUE)
                .addGroup(KeranjangPembeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, KeranjangPembeliLayout.createSequentialGroup()
                        .addGroup(KeranjangPembeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 814, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(totalKeranjangDisplay)
                            .addComponent(jLabel8))
                        .addGap(141, 141, 141))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, KeranjangPembeliLayout.createSequentialGroup()
                        .addComponent(refreshBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        KeranjangPembeliLayout.setVerticalGroup(
            KeranjangPembeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KeranjangPembeliLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addGap(4, 4, 4)
                .addComponent(totalKeranjangDisplay)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 206, Short.MAX_VALUE)
                .addComponent(refreshBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        MenuPembeli.addTab("Keranjang", KeranjangPembeli);

        jPanel1.setBackground(new java.awt.Color(196, 202, 196));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        jLabel9.setText("Riwayat Pemesanan");

        tableRiwayatTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tableRiwayatTransaksi);

        updateRiwayatTransaksi.setBackground(new java.awt.Color(85, 102, 85));
        updateRiwayatTransaksi.setText("Refresh");
        updateRiwayatTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateRiwayatTransaksiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(350, 350, 350)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(138, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 815, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(142, 142, 142))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(updateRiwayatTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel9)
                .addGap(54, 54, 54)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 309, Short.MAX_VALUE)
                .addComponent(updateRiwayatTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        MenuPembeli.addTab("Riwayat Pemesanan", jPanel1);

        ProfilePembeli.setBackground(new java.awt.Color(196, 202, 196));

        LogoutBTN.setBackground(new java.awt.Color(85, 102, 85));
        LogoutBTN.setText("Logout");
        LogoutBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutBTNActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Nama:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("Username:");

        UsernameUserProfile.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        UsernameUserProfile.setText("username user");

        NamaUserProfile.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        NamaUserProfile.setText("nama user");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel6.setText("No Telepon:");

        NoTelpUserProfile.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        NoTelpUserProfile.setText("no telpon user");

        UbahNama.setBackground(new java.awt.Color(85, 102, 85));
        UbahNama.setText("Ubah");
        UbahNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UbahNamaActionPerformed(evt);
            }
        });

        UbahUsername.setBackground(new java.awt.Color(85, 102, 85));
        UbahUsername.setText("Ubah");
        UbahUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UbahUsernameActionPerformed(evt);
            }
        });

        UbahNoTelpon.setBackground(new java.awt.Color(85, 102, 85));
        UbahNoTelpon.setText("Ubah");
        UbahNoTelpon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UbahNoTelponActionPerformed(evt);
            }
        });

        UbahPassword.setBackground(new java.awt.Color(85, 102, 85));
        UbahPassword.setText("Ubah Password");
        UbahPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UbahPasswordActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        jLabel13.setText("Profile");

        javax.swing.GroupLayout ProfilePembeliLayout = new javax.swing.GroupLayout(ProfilePembeli);
        ProfilePembeli.setLayout(ProfilePembeliLayout);
        ProfilePembeliLayout.setHorizontalGroup(
            ProfilePembeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProfilePembeliLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(480, 480, 480))
            .addGroup(ProfilePembeliLayout.createSequentialGroup()
                .addGap(299, 299, 299)
                .addGroup(ProfilePembeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(ProfilePembeliLayout.createSequentialGroup()
                        .addGroup(ProfilePembeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6)
                            .addComponent(jLabel1))
                        .addGap(10, 10, 10)
                        .addGroup(ProfilePembeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NamaUserProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NoTelpUserProfile)
                            .addComponent(UsernameUserProfile))
                        .addGap(124, 124, 124)
                        .addGroup(ProfilePembeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(UbahNama)
                            .addComponent(UbahUsername)
                            .addComponent(UbahNoTelpon)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProfilePembeliLayout.createSequentialGroup()
                        .addComponent(LogoutBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(UbahPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(282, Short.MAX_VALUE))
        );
        ProfilePembeliLayout.setVerticalGroup(
            ProfilePembeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProfilePembeliLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel13)
                .addGap(65, 65, 65)
                .addGroup(ProfilePembeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProfilePembeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(NamaUserProfile))
                    .addComponent(UbahNama, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(ProfilePembeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProfilePembeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(UsernameUserProfile))
                    .addComponent(UbahUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(ProfilePembeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(NoTelpUserProfile)
                    .addComponent(UbahNoTelpon, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addGroup(ProfilePembeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UbahPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LogoutBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(231, 231, 231))
        );

        MenuPembeli.addTab("Profile", ProfilePembeli);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MenuPembeli, javax.swing.GroupLayout.PREFERRED_SIZE, 1100, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MenuPembeli, javax.swing.GroupLayout.PREFERRED_SIZE, 735, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void LogoutBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutBTNActionPerformed
        UserSession.clearSession();
        
        Login LoginScreen = new Login();
        LoginScreen.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LogoutBTNActionPerformed

    private void UbahNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UbahNamaActionPerformed
        UbahNamaUser changeName = new UbahNamaUser();
        changeName.setVisible(true);
    }//GEN-LAST:event_UbahNamaActionPerformed

    private void UbahNoTelponActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UbahNoTelponActionPerformed
        UbahNoTelpon changeNoTelpon = new UbahNoTelpon();
        changeNoTelpon.setVisible(true);
    }//GEN-LAST:event_UbahNoTelponActionPerformed

    private void UbahPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UbahPasswordActionPerformed
        UbahPassword changePassword = new UbahPassword();
        changePassword.setVisible(true);
    }//GEN-LAST:event_UbahPasswordActionPerformed

    private void UbahUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UbahUsernameActionPerformed
        UbahUsername changeUsername = new UbahUsername();
        changeUsername.setVisible(true);
    }//GEN-LAST:event_UbahUsernameActionPerformed

    private void cariTokoBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariTokoBTNActionPerformed
        daftarTokoMakanan.removeAll();
        int rows = table_model.getRowCount();
        for (int i = rows - 1; i >= 0; i--) {
            table_model.removeRow(i);
        }
        
        Toko newToko = tokoCNTRL.getTokoByNama(cariToko.getText());
        if (newToko == null) {
            JOptionPane.showMessageDialog(null, "toko tidak ada", "Peringatan", JOptionPane.WARNING_MESSAGE);
        } else {
            Object[] returnSearch = {
                newToko.getId_toko(),
                newToko.getNamaToko(),
                newToko.getAlamatToko()
            };
            table_model.addRow(returnSearch);
        }
    }//GEN-LAST:event_cariTokoBTNActionPerformed

    private void updateDaftarTokoBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateDaftarTokoBTNActionPerformed
        daftarTokoMakanan.removeAll();
        int rows = table_model.getRowCount();
        for (int i = rows - 1; i >= 0; i--) {
            table_model.removeRow(i);
        }
        cariToko.setText("");
        
    }//GEN-LAST:event_updateDaftarTokoBTNActionPerformed

    private void daftarTokoMakananMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_daftarTokoMakananMouseClicked
        int selectedRow = daftarTokoMakanan.getSelectedRow();
        if (selectedRow != -1) {
            int idToko = (int) table_model.getValueAt(selectedRow, 0);
            String namaToko = table_model.getValueAt(selectedRow, 1).toString();
            String alamat = table_model.getValueAt(selectedRow, 2).toString();
            
            DetailToko detailtoko = new DetailToko();
            detailtoko.DetailToko(idToko, namaToko, alamat);
            detailtoko.setVisible(true);
        }
    }//GEN-LAST:event_daftarTokoMakananMouseClicked

    private void refreshBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBTNActionPerformed
        TableKeranjang.removeAll();
        int rows = tableModelKeranjang.getRowCount();
        for (int i = rows - 1; i >= 0; i--) {
            tableModelKeranjang.removeRow(i);
        }
        totalHargaKeranjang = 0;
        
        loadKeranjang(UserSession.getId());
        totalKeranjangDisplay.setText(String.valueOf(totalHargaKeranjang));
    }//GEN-LAST:event_refreshBTNActionPerformed

    private void TableKeranjangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableKeranjangMouseClicked
        // String[] judulTableKeranjang =  {"id Keranjang", "id Makanan","nama makanan", "jumlah pesanan", "harga"};
        int selectedRow = TableKeranjang.getSelectedRow();
        if (selectedRow != -1) {
            int id_keranjang = (int) tableModelKeranjang.getValueAt(selectedRow, 0);
            int id_makanan = (int) tableModelKeranjang.getValueAt(selectedRow, 1);
            String namaMakanan = tableModelKeranjang.getValueAt(selectedRow, 2).toString();
            int jumlahPesanan = (int) tableModelKeranjang.getValueAt(selectedRow, 3);
            double harga = (double) tableModelKeranjang.getValueAt(selectedRow, 4);
            
            Checkout CO = new Checkout();
            CO.Checkout(id_keranjang, UserSession.getId(), id_keranjang, jumlahPesanan, namaMakanan, namaMakanan, harga);
            CO.setVisible(true);
        }
    }//GEN-LAST:event_TableKeranjangMouseClicked

    private void updateRiwayatTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateRiwayatTransaksiActionPerformed
        tableRiwayatTransaksi.removeAll();
        int rows = tableModelTransaksi.getRowCount();
        
        for (int i = rows - 1; i >= 0; i--) {
            tableModelTransaksi.removeRow(i);
        }
        
        loadTransaksi(UserSession.getId());
    }//GEN-LAST:event_updateRiwayatTransaksiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPembeli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPembeli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPembeli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPembeli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPembeli().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel HomePembeli;
    private javax.swing.JPanel KeranjangPembeli;
    private javax.swing.JButton LogoutBTN;
    private javax.swing.JTabbedPane MenuPembeli;
    private javax.swing.JLabel NamaUserHome;
    private javax.swing.JLabel NamaUserProfile;
    private javax.swing.JLabel NoTelpUserProfile;
    private javax.swing.JPanel ProfilePembeli;
    private javax.swing.JLabel SelamatDatang;
    private javax.swing.JTable TableKeranjang;
    private javax.swing.JButton UbahNama;
    private javax.swing.JButton UbahNoTelpon;
    private javax.swing.JButton UbahPassword;
    private javax.swing.JButton UbahUsername;
    private javax.swing.JLabel UsernameUserProfile;
    private javax.swing.JTextField cariToko;
    private javax.swing.JButton cariTokoBTN;
    private javax.swing.JTable daftarTokoMakanan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton refreshBTN;
    private javax.swing.JTable tableRiwayatTransaksi;
    private javax.swing.JLabel totalKeranjangDisplay;
    private javax.swing.JButton updateDaftarTokoBTN;
    private javax.swing.JButton updateRiwayatTransaksi;
    // End of variables declaration//GEN-END:variables
}
